export const LOAD_MUSIC_REQUEST = 'PLAYER/LOAD_MUSIC/REQUEST';
export const LOAD_MUSIC_SUCCESS = 'PLAYER/LOAD_MUSIC/SUCCESS';
export const LOAD_MUSIC_FAILURE = 'PLAYER/LOAD_MUSIC/FAILURE';

export const PLAY_MUSIC_REQUEST = 'PLAYER/PLAY_MUSIC/REQUEST';
export const PLAY_MUSIC_SUCCESS = 'PLAYER/PLAY_MUSIC/SUCCESS';
export const PLAY_MUSIC_FAILURE = 'PLAYER/PLAY_MUSIC/FAILURE';

export const PAUSE_MUSIC_REQUEST = 'PLAYER/PAUSE_MUSIC/REQUEST';
export const PAUSE_MUSIC_SUCCESS = 'PLAYER/PAUSE_MUSIC/SUCCESS';
export const PAUSE_MUSIC_FAILURE = 'PLAYER/PAUSE_MUSIC/FAILURE';

export const CHANGE_MUSIC_REQUEST = 'PLAYER/CHANGE_MUSIC/REQUEST';

export const NEXT_MUSIC_REQUEST = 'PLAYER/NEXT_MUSIC/REQUEST';
export const PREV_MUSIC_REQUEST = 'PLAYER/PREV_MUSIC/REQUEST';

export const SET_CURRENT_INDEX = 'PLAYER/SET_INDEX/REQUEST';

export const STOP_MUSIC_REQUEST = 'PLAYER/STOP_MUSIC/REQUEST';
export const STOP_MUSIC_SUCCESS = 'PLAYER/STOP_MUSIC/SUCCESS';
export const STOP_MUSIC_FAILURE = 'PLAYER/STOP_MUSIC/FAILURE';

export const SET_MUSIC_DURATION = 'PLAYER/SET_DURATION/REQUEST';

export const SET_MUSIC_POSITION = 'PLAYER/SET_POSITION/REQUEST';

export const CHANGE_PLAYLIST = 'PLAYER/CHANGE_PLAYLIST';

export const CHANGE_SAVED_PARAM = 'PLAYER/CHANGE_SAVED_PARAM';
