export const GET_PAGINATED_USERS = 'USERS/GET_PAGINATED_USERS/REQUEST';
export const GET_PAGINATED_USERS_SUCCESS = 'USERS/GET_PAGINATED_USERS/SUCCESS';
export const GET_PAGINATED_USERS_FAILURE = 'USERS/GET_PAGINATED_USERS/FAILURE';

export const GET_USER_INFO = 'USERS/GET_USER_INFO/REQUEST';
export const GET_USER_INFO_SUCCESS = 'USERS/GET_USER_INFO/SUCCESS';
export const GET_USER_INFO_FAILURE = 'USERS/GET_USER_INFO/FAILURE';

export const APPROVE_USER = 'USERS/APPROVE_USER/REQUEST';
export const APPROVE_USER_SUCCESS = 'USERS/APPROVE_USER/SUCCESS';
export const APPROVE_USER_FAILURE = 'USERS/APPROVE_USER/FAILURE';

export const REJECT_USER = 'USERS/REJECT_USER/REQUEST';
export const REJECT_USER_SUCCESS = 'USERS/REJECT_USER/SUCCESS';
export const REJECT_USER_FAILURE = 'USERS/REJECT_USER/FAILURE';

export const PROMOTE_USER = 'USERS/PROMOTE_USER/REQUEST';
export const PROMOTE_USER_SUCCESS = 'USERS/PROMOTE_USER/SUCCESS';
export const PROMOTE_USER_FAILURE = 'USERS/PROMOTE_USER/FAILURE';

export const UPDATE_LOGGED_USER_INFO = 'USERS/UPDATE_LOGGED_USER_INFO/REQUEST';
export const UPDATE_LOGGED_USER_DATA = 'USERS/UPDATE_LOGGED_USER_DATA/REQUEST';
